# Generated by Django 3.2.8 on 2022-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20220127_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Фото'),
        ),
    ]
